
use klv::key::partition::PartitionStatus;

#[derive(Debug, PartialEq, Clone)]
pub enum KeyIdentifier {
  HeaderPartition{status: PartitionStatus},
  BodyPartition{status: PartitionStatus},
  FooterPartition{status: PartitionStatus},
  PrimerPack,
  RandomIndexMetadata,

  SystemItemElement,
  IndexTableSegment,

  SystemItemSystemMetadataPack,
  SystemItemPackageMetadataSet,

  SequenceSet,
  SourceClipSet,
  TimecodeComponentSet,
  ContentStorageSet,
  EssenceContainerDataSet,
  FileDescriptorSet,
  GenericPictureEssenceDescriptor,
  CdciVideoDescriptor,
  RgbaVideoDescriptor,
  PrefaceSet,
  IdentificationSet,
  NetworkLocatorSet,
  TextLocatorSet,
  MaterialPackageSet,
  FilePackageSet,
  StaticTrackSet,
  TrackSet,
  EventTrackSet,
  DmSegmentDescriptorSet,
  GenericSoundEssenceDescriptorSet,
  GenericDataEssenceDescriptorSet,
  MultipleDescriptorSet,
  DmSourceClipSet,
  Aes3AudioDescriptorSet,
  WaveAudioDescriptorSet,
  MpegVideoDescriptorSet,
  Jpeg2000SubDescriptorSet,
  McaLabelSubDescriptorSet,
  AudioChannelLabelSubDescriptorSet,
  SoundfieldGroupLabelSubDescriptorSet,

  PictureItemMpegFrameWrappedPictureElement,
  Jpeg2000FrameWrapped,
  Jpeg2000ClipWrapped,
  SoundItemDataWrappedSoundElement,
  SoundItemWaveDataWrappedSoundElement,
  SoundItemBwfDataWrappedSoundElement,

  AS10CoreFramework,
  AS10ShimName,
  AS10Type,
  AS10MainTitle,
  AS10SubTitle,
  AS10TitleDescription,
  AS10OrganizationName,
  AS10PersonName,
  AS10LocationDescription,
  AS10CommonSpanningID,
  AS10SpanningNumber,
  AS10CumulativeDuration,

  FillItem,
  FillItemAvid,
  Unknown,
}
